version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:3.5.17
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - neo4j-net
    ports:
      - '7474:7474'
      - '7687:7687'
  app:
    container_name: goneo4jgql
    image: goneo4jgql
    build: ./
    networks:
      - neo4j-net
    ports:
      - '8080:8080'
    depends_on:
      - neo4j
    environment:
      - NEO4J_PROTO=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test

networks:
  neo4j-net:
    driver: 'bridge'
